//fazendo acesso assincrono a API (usando await para aguardar a resposta)
const fetchPokemon = async (pokemon) => {
    const APIResponse = await fetch(`https://pokeapi.co/api/v2/pokemon/${pokemon}`);
    console.log(APIResponse);

    //acessando os dados json da consulta API:
    const data = await APIResponse.json();
    console.log(data);
    console.log("Nome do pokemon: "+data.name);
    console.log("Numero do pokemon: "+data.id);
    console.log("Tipo do pokemon: "+ data['types']['0']['type']['name']);
    console.log("Ataques: "+ data['moves']['0']['move']['name']
    + ", " + data['moves']['0']['move']['name']
    + ", " + data['moves']['1']['move']['name']
    + ", " + data['moves']['2']['move']['name']
    + ", " + data['moves']['3']['move']['name']
    + ", " + data['moves']['4']['move']['name']
    + ", " + data['moves']['5']['move']['name']
    + ", " + data['moves']['6']['move']['name']
    + ", " + data['moves']['7']['move']['name']
    + ", " + data['moves']['8']['move']['name']
    + ", " + data['moves']['9']['move']['name']
    + ", " + data['moves']['10']['move']['name']
    + ", " + data['moves']['11']['move']['name']
    + ", " + data['moves']['12']['move']['name']
    + ", " + data['moves']['13']['move']['name']
    + ", " + data['moves']['14']['move']['name']
    + ", " + data['moves']['15']['move']['name']
    + ", " + data['moves']['16']['move']['name']
    + ", " + data['moves']['17']['move']['name']
    + ", " + data['moves']['18']['move']['name']
    + ", " + data['moves']['19']['move']['name']
    + ", " + data['moves']['20']['move']['name']
    + ", " + data['moves']['21']['move']['name']
    + ", " + data['moves']['22']['move']['name']
    + ", " + data['moves']['23']['move']['name']
    + ", " + data['moves']['24']['move']['name']
    + ", " + data['moves']['25']['move']['name']
    + ", " + data['moves']['26']['move']['name']
    + ", " + data['moves']['27']['move']['name']
    + ", " + data['moves']['28']['move']['name']
    + ", " + data['moves']['29']['move']['name']
    + ", " + data['moves']['30']['move']['name']
    + ", " + data['moves']['31']['move']['name']
    + ", " + data['moves']['32']['move']['name']
    + ", " + data['moves']['33']['move']['name']
    + ", " + data['moves']['34']['move']['name']
    + ", " + data['moves']['35']['move']['name']
    + ", " + data['moves']['36']['move']['name']
    + ", " + data['moves']['37']['move']['name']
    + ", " + data['moves']['38']['move']['name']
    + ", " + data['moves']['39']['move']['name']
    + ", " + data['moves']['40']['move']['name']
    + ", " + data['moves']['41']['move']['name']
    + ", " + data['moves']['42']['move']['name']
    + ", " + data['moves']['43']['move']['name']
    + ", " + data['moves']['44']['move']['name']
    + ", " + data['moves']['45']['move']['name']
    + ", " + data['moves']['46']['move']['name']
    + ", " + data['moves']['47']['move']['name']
    + ", " + data['moves']['48']['move']['name']
    + ", " + data['moves']['49']['move']['name']
    + ", " + data['moves']['50']['move']['name']
    + ", " + data['moves']['51']['move']['name']
    + ", " + data['moves']['52']['move']['name']
    + ", " + data['moves']['53']['move']['name']
    + ", " + data['moves']['54']['move']['name']
    + ", " + data['moves']['55']['move']['name']
    + ", " + data['moves']['56']['move']['name']
    + ", " + data['moves']['57']['move']['name']
    + ", " + data['moves']['58']['move']['name']
    + ", " + data['moves']['59']['move']['name']
    + ", " + data['moves']['60']['move']['name']
    + ", " + data['moves']['61']['move']['name']
    + ", " + data['moves']['62']['move']['name']
    + ", " + data['moves']['63']['move']['name']
    + ", " + data['moves']['64']['move']['name']
    + ", " + data['moves']['65']['move']['name']
    + ", " + data['moves']['66']['move']['name']
    + ", " + data['moves']['67']['move']['name']
    + ", " + data['moves']['68']['move']['name']
    + ", " + data['moves']['69']['move']['name']
    + ", " + data['moves']['70']['move']['name']
    + ", " + data['moves']['71']['move']['name']
    + ", " + data['moves']['72']['move']['name']
    + ", " + data['moves']['73']['move']['name']
    + ", " + data['moves']['74']['move']['name']
    + ", " + data['moves']['75']['move']['name']
    + ", " + data['moves']['76']['move']['name']
    + ", " + data['moves']['77']['move']['name']
    + ", " + data['moves']['78']['move']['name']
    + ", " + data['moves']['79']['move']['name']
    + ", " + data['moves']['80']['move']['name']
    + ", " + data['moves']['81']['move']['name']
    + ", " + data['moves']['82']['move']['name']
    + ", " + data['moves']['83']['move']['name']
    + ", " + data['moves']['84']['move']['name']
    + ", " + data['moves']['85']['move']['name']
    + ", " + data['moves']['86']['move']['name']
    + ", " + data['moves']['87']['move']['name']
    + ", " + data['moves']['88']['move']['name']
    + ", " + data['moves']['89']['move']['name']
    + ", " + data['moves']['90']['move']['name']
    + ", " + data['moves']['91']['move']['name']
    + ", " + data['moves']['92']['move']['name']
    + ", " + data['moves']['93']['move']['name']
    + ", " + data['moves']['94']['move']['name']
    + ", " + data['moves']['95']['move']['name']);
 
}

fetchPokemon('25');